version: '2'
services:
    melo:
        container_name: meloapp
        build:
            context: /
            dockerfile: Dockerfile
        depends_on:
            - postgres
            - keycloak
        restart: always
        ports:
            - 8080:8080
        networks:
            - mynetwork
    postgres:
        container_name: postgresdb
        image: postgres:latest
        volumes:
            - /data:/var/lib/postgresql/data
        environment:
            POSTGRES_USER: sa
            POSTGRES_PASSWORD: sa
        ports:
            - 5432:5432
        networks:
            - mynetwork
    keycloak:
        container_name: keycloak
        image: quay.io/keycloak/keycloak:latest
        volumes:
            - ./realm/:/opt/keycloak/data/import
        environment:
            KEYCLOAK_ADMIN: admin
            KEYCLOAK_ADMIN_PASSWORD: admin
            KC_HTTP_PORT: 8081
            KC_HOSTNAME: keycloak
        command: 
            start-dev --import-realm
        ports:
            - 8081:8081
        networks:
            - mynetwork
networks:
    mynetwork:
        driver: bridge