package pl.envelo.melo.domain.notification;

public enum NotificationType {
    EVENT_UPDATED, EVENT_ORGANIZER_UPDATED, EVENT_DATE_CHANGED, EVENT_LOCATION_CHANGED, INVITE,
    UNIT_UPDATED, UNIT_OWNERSHIP_REVOKED, UNIT_OWNERSHIP_GRANTED,
    CATEGORY_REQUEST_REJECTED, CATEGORY_REQUEST_ACCEPTED
}
