package pl.envelo.melo.domain.event;

public enum EventType {
    LIMITED_EXTERNAL, UNLIMITED_EXTERNAL, LIMITED_PUBLIC_INTERNAL,
    UNLIMITED_PUBLIC_INTERNAL, LIMITED_PRIVATE_INTERNAL, UNLIMITED_PRIVATE_INTERNAL 
}
